name: compliance

on:
  pull_request:

permissions:
  contents: read

jobs:
  # Reference: ENGSRV-059
  copywrite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: hashicorp/setup-copywrite@867a1a2a064a0626db322392806428f7dc59cb3e # v1.1.2
      - run: copywrite headers --plan
      - run: copywrite license --plan